# Generated by Django 4.1.1 on 2022-09-11 09:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("persons", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="RecyclePerson",
            fields=[],
            options={
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("persons.person",),
        ),
    ]
